config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "static_pages#home"
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions]
  as :user do
    get "login", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    match "logout", to: "devise/sessions#destroy", as: :destroy_user_session,
      via: Devise.mappings[:user].sign_out_via
  end

  resources :users, only: [:show, :index] do
    resources :following, :followers, only: :index
  end
  resources :words
  resources :categories, only: [:index, :show]
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: :index
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :searches

  namespace :api do
    resources :categories, only: [:index, :show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :lessons, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :choices
  has_many :learned_words, ->{where(choices: {is_correct_answer: :right})},
    through: :choices, source: :word
  has_many :answers, through: :choices
  has_many :chatroom_users
  has_many :joined_rooms, through: :chatroom_users, source: :chatroom
  has_many :messages

  validates :name, presence: true

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete(other_user)
  end

  def following? other_user
    following.include?(other_user)
  end

  class << self
    def new_with_session params, session
      super.tap do |user|
        if data == session["devise.facebook_data"] &&
          session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end

    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def generic_callback provider
    @identity = User.from_omniauth(request.env["omniauth.auth"])
    @user = @identity || current_user
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def facebook
    generic_callback "facebook"
  end

  def google_oauth2
    generic_callback "google"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @pagy, @users = pagy User.all, items: 30
  end

  def show
    @user = User.find_by id: params[:id]
    @lesson = @user.lessons.build
    @pagy, @lessons = pagy @user.lessons.order_created_desc.includes(:category),
      items: 10
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit t(".follow"), class: "btn follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <% if current_user.following? user %>
    <%= render "users/unfollow" %>
  <% else %>
    <%= render "users/follow" %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
  html: {method: :delete}, remote: true do |f| %>
<%= f.submit t(".unfollow"), class: "btn follow" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide :title, t(".users") %>
<h1><%= t ".users" %></h1>

<ul class="users">
  <%= render @users %>
</ul>

<%== pagy_bootstrap_nav @pagy %>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<h1><%= @user.name %></h1>
<span id="follow_form">
  <%= render "follow_form", user: @user %>
</span>
<a href="<%= user_followers_path @user %>">
  <b id="followers"><%= @user.followers.count %></b> <%= t ".followers" %>
</a>
<a href="<%= user_following_index_path @user %>">
  <b id="following"><%= @user.following.count %></b> <%= t ".following" %>
</a>

<% if @user == current_user %>
  <div class="list-group-item">
    <%= render "lessons/form" %>
  </div>
<% end %>

<h2><%= t(".lessons", count: @pagy.count) %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= t ".lesson" %></th>
      <th scope="col"><%= t ".created_at" %></th>
      <th scope="col"><%= t ".result" %></th>
      <th scope="col"><%= t ".action" %></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.full_title %></td>
        <td><%= l(lesson.created_at, format: :day) %></td>
        <td><%= t(".right_choices", count: lesson.right_choices.size) %></td>
        <td>
          <% if lesson.not_answer? %>
            <% if @user == current_user %>
              <%= link_to t(".answer"), edit_lesson_path(lesson) %>
            <% else %>
              <%= t ".not_answer" %>
            <% end %>
          <% elsif lesson.answered? %>
            <%= link_to t(".view"), lesson_path(lesson) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav @pagy %>

app/views/users/show_follow.html.erb
<% provide :title, @title %>

<h1 class="title"><%= @title %></h1>
  <% if @users.present? %>
    <ul class="row">
      <%= render @users %>
    </ul>
  <% end %>
  <%== pagy_bootstrap_nav @pagy %>
<%= link_to t(".back"), user_path(@user) %>