config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root "static_pages#home"
  devise_for :users, controllers: {registrations: "registrations",
    omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions]
  as :user do
    get "login", to: "devise/sessions#new", as: :new_user_session
    post "login", to: "devise/sessions#create", as: :user_session
    match "logout", to: "devise/sessions#destroy", as: :destroy_user_session,
      via: Devise.mappings[:user].sign_out_via
  end

  resources :users, only: [:show, :index] do
    resources :following, :followers, only: :index
  end
  resources :words
  resources :categories, only: [:index, :show]
  resources :lessons
  resources :relationships, only: [:create, :destroy]
  resources :activities, only: :index
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
  resources :searches

  namespace :api do
    resources :categories, only: [:index, :show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  has_many :lessons, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :choices
  has_many :learned_words, ->{where(choices: {is_correct_answer: :right})},
    through: :choices, source: :word
  has_many :answers, through: :choices
  has_many :chatroom_users
  has_many :joined_rooms, through: :chatroom_users, source: :chatroom
  has_many :messages

  validates :name, presence: true

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete(other_user)
  end

  def following? other_user
    following.include?(other_user)
  end

  class << self
    def new_with_session params, session
      super.tap do |user|
        if data == session["devise.facebook_data"] &&
          session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
        end
      end
    end

    def from_omniauth auth
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
      end
    end
  end
end

app/models/word.rb
require 'elasticsearch/model'

class Word < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :category
  has_many :lesson_words
  has_many :answers, inverse_of: :word, dependent: :destroy
  has_one :right_answer, ->{where(correct: :right)}, class_name: "Answer"
  has_many :choices

  validates :content, presence: true
  validates :category_id, presence: true

  accepts_nested_attributes_for :answers, reject_if: :all_blank,
    allow_destroy: true

  after_save :check_condition

  scope :all_words, -> do
    includes :category, :right_answer
  end

  settings do
    mappings dynamic: false do
      indexes :content, type: :text, analyzer: :english
    end
  end

  private
  def check_condition
    if answers.count != 4 || answers.right.count != 1
      raise ActiveRecord::RecordInvalid.new(self)
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  load_and_authorize_resource
  before_action :find_word
  include WordsHelper

  def index
    @pagy, @words = pagy Word.all_words.
      order(sort_column.to_s + " " + sort_direction), items: 30
    @learned_word_ids = current_user.learned_words.pluck(:id)
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t ".success"
      redirect_to words_path
    else
      flash[:danger] = t ".fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t ".success"
      redirect_to words_path
    else
      flash[:danger] = t ".fail"
      render :edit
    end
  end

  private
  def find_word
    @word = Word.find_by id: params[:id]
  end

  def word_params
    params.require(:word).permit :category_id, :content,
      answers_attributes: [:id, :word_id, :content, :correct, :_destroy]
  end
end

app/helpers/words_helper.rb
module WordsHelper
  JOINED_TABLE_COLUMNS = %w[categories.title]
  def sort_column
    if (JOINED_TABLE_COLUMNS || Word.column_names).include?(params[:sort])
      params[:sort]
    else 
      :content
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/words/_answer_fields.html.erb
<fieldset>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content, placeholder: t(".insert_answer") %>
  </div>
  <div class="field">
    <%= f.label :correct %>
    <%= f.collection_radio_buttons :correct, Answer.corrects.map{|key, value| [t(".#{key}"), key]}, :last, :first %>
  </div>
  <%= f.hidden_field :_destroy %>
  <%= link_to t(".remove"), '#', class: "remove_fields" %>
</fieldset>

app/views/words/_form.html.erb
<%= form_for @word do |f| %>
  <div class="field">
    <%= f.label :categogy, t(".choose") %>
    <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :title), class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content, placeholder: t(".insert"), class: "form-control" %>
  </div>
  <h3><%= t ".answers" %></h3>
    <div class="field">
      <%= f.fields_for :answers do |answer| %>
        <%= render "answer_fields", f: answer %>
      <% end %>
      <div>
        <%= link_to_add_fields t(".add"), f, :answers %>
      </div>
    </div>
  <div class="field">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<% provide :title, t(".edit") %>

<h1><%= t ".edit" %></h1>
  <div class="col-md-8">
    <%= render "form" %>
  </div>

app/views/words/index.html.erb
<% provide :title, t(".word_list") %>
<h1><%= t ".word_list" %></h1>
<div>
  <% if current_user.has_role? :admin %>
    <%= link_to t(".new_word"), new_word_path, class: "btn btn-success" %>
  <% end %>
</div><br>

<div class="form-inline col-xs-2"><%= render "searches/form" %></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= sortable "content", t(".word") %></th>
      <th scope="col"><%= t ".meaning" %></th>
      <th scope="col"><%= sortable "categories.title", t(".category") %></th>
      <th scope="col"><%= t ".learned" %></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.content %></td>
        <td><%= word.right_answer.content if word.right_answer.present? %></td>
        <td><%= word.category.title %></td>
        <td>
          <% if @learned_word_ids.include?(word.id) %>
            <i class="fa fa-check-circle green"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_bootstrap_nav @pagy %>

app/views/words/new.html.erb
<% provide :title, t(".create") %> 

<h1><%= t ".create" %></h1>
  <div class="col-md-8">
    <%= render "form" %>
  </div>